src/Entity/Paste.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PasteRepository")
 */
class Paste
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string")
     * @Assert\NotBlank
     */
    private $language;

    /**
     * @ORM\Column(type="string")
     * @Assert\NotBlank
     */
    private $title;

    /** @ORM\Column(type="datetime") */
    private $edit_date;

    /**
     * @ORM\ManyToOne(targetEntity="PastebinUser", inversedBy="pastes")
     * @ORM\JoinColumn(name="author_id", referencedColumnName="id", nullable=true)
     */
    private $author;

    /** @ORM\Column(type="string") */
    private $fileName;

    /** @ORM\Column(type="boolean") */
    private $visibility;
    //TODO: Add "visibility" field


    /**
     * @Assert\NotBlank
     */
    private $content;

    //*************** GETTERS & SETTERS ******************//

    public function getId()
    {
        return $this->id;
    }

    public function setId($id): void
    {
        $this->id = $id;
    }

    public function getLanguage()
    {
        return $this->language;
    }

    public function setLanguage($language): void
    {
        $this->language = $language;
    }

    public function getTitle()
    {
        return $this->title;
    }

    public function setTitle($title): void
    {
        $this->title = $title;
    }

    public function getContent()
    {
        return $this->content;
    }

    public function setContent($content): void
    {
        $this->content = $content;
    }

    public function getEditDate()
    {
        return $this->edit_date;
    }

    public function setEditDate($edit_date): void
    {
        $this->edit_date = $edit_date;
    }

    public function getAuthor()
    {
        return $this->author;
    }

    public function setAuthor($author): void
    {
        $this->author = $author;
    }

    public function getFilename()
    {
        return $this->fileName;
    }

    public function setFilename($fileName): void
    {
        $this->fileName = $fileName;
    }


}

templates/Dashboard/dashboard.html.twig
{% extends 'base.html.twig' %}


{# Template dashbord #}
{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-4">
                {% include 'Dashboard/dashnav.html.twig' %}
            </div>
            <div class="col-8" id="result">Placeholder</div>
        </div>
    </div>
{% endblock %}

templates/Dashboard/dashnav.html.twig
{% import 'navigation.html.twig' as nav %}
<ul class="nav flex-column">
    {{ nav.navitem('Uploaded Pastes', '#', 'justify-content-center') }}
</ul>

templates/Dashboard/pastelist.html.twig
<div class="flex-column">
    {% for paste in pastes %}
        <div class="d-flex">
            <a class="mr-auto p-2" href="{{ path('display', {'paste_name': paste.filename }) }}">{{ paste.title }}</a>
            <a class="p-2" href="#">addFav</a>
            <a class="p-2" href="#">edit</a>
            <a class="p-2" href="#">delete</a>
        </div>
    {% endfor %}
</div>